import Link from "next/link";

import { Cluster, Container, InstrumentRule, Panel, Section, SectionHeader, StatusLabel } from "@/components/ui";

const statusExplanations = [
  ["early", "EARLY", "An early analytical context with limited history or developing evidence."],
  ["trending", "TRENDING", "A reviewed pattern of activity, not a promise about future performance."],
  ["high-risk", "HIGH RISK", "A clear risk context that should remain prominent in any published view."],
] as const;

const evidenceExplanations = [
  ["verified-data", "VERIFIED DATA", "A sourceable, deterministic input with stated provenance and time."],
  ["strong-signal", "STRONG SIGNAL", "Multiple indicators support an interpretation; it remains contextual."],
  ["ai-inference", "AI INFERENCE", "Model-assisted interpretation, kept separate from verified facts."],
  ["unknown", "UNKNOWN", "Unavailable, incomplete, unsupported, or insufficient data. It is not zero or safe."],
] as const;

const evaluationAreas = [
  ["01", "Market Structure", "Structure and activity context where a supported source exists."],
  ["02", "Liquidity", "Liquidity conditions with units, window, source, and freshness."],
  ["03", "Trading Activity", "Observed activity patterns, never a direction or action."],
  ["04", "Holder / Wallet Concentration", "Concentration context where the chain and provider support it."],
  ["05", "Token Age", "Age as a bounded input, not a quality shortcut."],
  ["06", "Contract / Technical Risk", "Technical risk signals with explicit chain authority."],
  ["07", "Momentum", "Time-bounded changes, not a forecast."],
  ["08", "Narrative / Social Context", "Separate context that may be model-assisted and uncertain."],
  ["09", "Freshness", "How recent and usable the underlying observations remain."],
] as const;

export default function RadarPageContent({ radarEnabled }: { radarEnabled: boolean }) {
  return (
    <div>
      <Section className="pb-12 sm:pb-20"><Container size="wide"><div className="grid gap-12 lg:grid-cols-[1.15fr_0.85fr] lg:items-end"><div><div className="flex flex-wrap items-center gap-2"><StatusLabel kind="radar" /><span className="font-mono text-[0.625rem] uppercase tracking-[0.16em] text-[var(--n100-text-tertiary)]">Watch-only intelligence</span></div><h1 className="mt-6 max-w-4xl text-5xl font-semibold tracking-[-0.06em] text-[var(--n100-text-primary)] sm:text-7xl">Market intelligence before the noise.</h1><p className="mt-7 max-w-2xl text-base leading-7 text-[var(--n100-text-secondary)] sm:text-lg">Radar organizes structured market context, separates evidence from inference, and keeps risk and freshness visible before any intelligence is considered for publication.</p><Cluster className="mt-8" gap="md"><Link className="inline-flex min-h-10 items-center justify-center rounded-[var(--n100-radius-control)] bg-[var(--n100-accent)] px-4 text-sm font-semibold text-[#11201a] hover:bg-[var(--n100-accent-strong)]" href="/methodology">Read Methodology</Link><Link className="inline-flex min-h-10 items-center justify-center rounded-[var(--n100-radius-control)] border border-[var(--n100-border-strong)] px-4 text-sm font-semibold text-[var(--n100-text-primary)] hover:border-[var(--n100-accent)] hover:text-[var(--n100-accent)]" href="#how-radar-works">Explore how Radar works</Link></Cluster></div><Panel family="radar" padding="lg"><p className="font-mono text-[0.625rem] font-semibold uppercase tracking-[0.18em] text-[var(--n100-radar)]">Intelligence model</p><p className="mt-5 text-2xl font-semibold tracking-[-0.04em] text-[var(--n100-text-primary)]">Discover → Filter → Analyze → Review → Publish</p><p className="mt-5 text-sm leading-6 text-[var(--n100-text-secondary)]">Automation may help organize inputs. Human review remains required before public publication.</p><InstrumentRule className="mt-8" /></Panel></div></Container></Section>

      <Section density="compact" className="border-y border-[var(--n100-border-subtle)] bg-[var(--n100-surface-secondary)]/35"><Container size="wide"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-[0.625rem] font-semibold uppercase tracking-[0.18em] text-[var(--n100-radar)]">Current public state</p><p className="mt-2 text-lg font-semibold tracking-[-0.02em] text-[var(--n100-text-primary)]">{radarEnabled ? "Radar availability is staged; no live records are published yet." : "Radar public feed is currently not active."}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--n100-text-secondary)]">The public product explanation is available now. Live records will appear only after real data infrastructure, publication controls, and review validation are complete.</p></div><span className="shrink-0 border border-[var(--n100-border-strong)] px-3 py-2 font-mono text-[0.625rem] uppercase tracking-[0.14em] text-[var(--n100-text-tertiary)]">{radarEnabled ? "STAGED · NO LIVE DATA" : "INACTIVE · NO LIVE DATA"}</span></div></Container></Section>

      <Section id="how-radar-works"><Container size="wide"><SectionHeader eyebrow="01 / Intelligence model" title="Context first. Publication second." description="Radar is designed as a reviewable intelligence workflow, not an action surface. Each stage preserves what is known, what is inferred, and what remains unavailable." /><div className="mt-8 grid gap-4 md:grid-cols-5">{["DISCOVERED", "SCREENED", "ANALYZED", "READY FOR REVIEW", "PUBLISHED"].map((stage, index) => <div key={stage} className="border-t-2 border-[var(--n100-radar)]/55 pt-4"><p className="font-mono text-xs text-[var(--n100-radar)]">0{index + 1}</p><p className="mt-3 text-xs font-semibold uppercase tracking-[0.13em] text-[var(--n100-text-primary)]">{stage}</p><p className="mt-3 text-sm leading-6 text-[var(--n100-text-tertiary)]">{index === 4 ? "Only approved intelligence can reach the public surface." : "A distinct internal stage with its own evidence and state."}</p></div>)}</div></Container></Section>

      <Section className="border-y border-[var(--n100-border-subtle)] bg-[var(--n100-surface-subtle)]"><Container size="wide"><SectionHeader eyebrow="02 / Status and evidence" title="Labels should make uncertainty easier to read." description="Analytical status is context, not a recommendation. Evidence types remain separate so a missing or model-assisted input cannot look like verified data." /><div className="mt-8 grid gap-6 lg:grid-cols-2"><Panel family="radar" padding="lg"><p className="font-mono text-[0.625rem] uppercase tracking-[0.16em] text-[var(--n100-radar)]">Analytical status</p><div className="mt-6 space-y-5">{statusExplanations.map(([kind, label, description]) => <div key={label} className="flex items-start gap-4"><StatusLabel kind={kind} /><p className="pt-1 text-sm leading-6 text-[var(--n100-text-secondary)]">{description}</p></div>)}</div><p className="mt-7 border-t border-[var(--n100-border-subtle)] pt-5 text-xs leading-5 text-[var(--n100-text-tertiary)]">REJECTED remains an internal analytical outcome and is not presented as a normal public opportunity state.</p></Panel><Panel padding="lg"><p className="font-mono text-[0.625rem] uppercase tracking-[0.16em] text-[var(--n100-text-tertiary)]">Evidence states</p><div className="mt-6 space-y-5">{evidenceExplanations.map(([kind, label, description]) => <div key={label} className="flex items-start gap-4"><StatusLabel kind={kind} /><p className="pt-1 text-sm leading-6 text-[var(--n100-text-secondary)]">{description}</p></div>)}</div></Panel></div></Container></Section>

      <Section><Container size="wide"><SectionHeader eyebrow="03 / What Radar evaluates" title="Categories follow the available evidence." description="Coverage varies by chain, provider, observation window, and source quality. Radar does not claim every category exists for every token." /><div className="mt-8 grid gap-x-8 sm:grid-cols-2 lg:grid-cols-3">{evaluationAreas.map(([number, label, description]) => <div key={label} className="border-b border-[var(--n100-border-subtle)] py-5"><span className="font-mono text-xs text-[var(--n100-accent)]">{number}</span><h3 className="mt-3 text-sm font-semibold uppercase tracking-[0.13em] text-[var(--n100-text-primary)]">{label}</h3><p className="mt-2 text-sm leading-6 text-[var(--n100-text-tertiary)]">{description}</p></div>)}</div></Container></Section>

      <Section className="border-y border-[var(--n100-border-subtle)] bg-[var(--n100-surface-secondary)]/35"><Container size="wide"><div className="grid gap-6 lg:grid-cols-2"><Panel padding="lg"><SectionHeader eyebrow="04 / Freshness" title="Time belongs beside the number." description="Radar intelligence is time-sensitive. Fresh, aging, stale, and unknown inputs should remain visible instead of being silently replaced." /><div className="mt-7 flex flex-wrap gap-2">{(["FRESH", "AGING", "STALE", "UNKNOWN"] as const).map((state) => <span key={state} className="border border-[var(--n100-border-strong)] px-3 py-2 font-mono text-[0.625rem] font-semibold uppercase tracking-[0.14em] text-[var(--n100-text-secondary)]">{state}</span>)}</div><p className="mt-7 text-sm leading-6 text-[var(--n100-text-secondary)]">Unavailable data is UNKNOWN, not zero. Stale data is marked as stale and can make a record ineligible for publication.</p></Panel><Panel family="radar" padding="lg"><SectionHeader eyebrow="05 / Review" title="Human review is part of the product." description="Automatic public publishing is OFF by default. A reviewed state is not the same thing as a score or a provider response." /><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Sources and provenance", "Risk and unknowns", "Methodology version", "Publication eligibility"].map((item) => <div key={item} className="border-l border-[var(--n100-radar)]/50 pl-3 text-sm text-[var(--n100-text-secondary)]">{item}</div>)}</div></Panel></div></Container></Section>

      <Section><Container size="content"><Panel family="commercial" padding="lg"><p className="font-mono text-[0.625rem] font-semibold uppercase tracking-[0.17em] text-[var(--n100-sponsored)]">Commercial independence</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.045em] text-[var(--n100-text-primary)]">Sponsored ≠ Radar ranking.</h2><p className="mt-5 max-w-2xl text-sm leading-6 text-[var(--n100-text-secondary)]">Sponsored placements cannot purchase Radar Score, ranking, risk, evidence, analytical status, or organic visibility. Commercial presentation stays separate from Radar output.</p><div className="mt-7 flex flex-wrap gap-4"><Link className="text-sm font-semibold text-[var(--n100-accent)] underline underline-offset-4" href="/methodology">Methodology and transparency</Link><Link className="text-sm font-semibold text-[var(--n100-accent)] underline underline-offset-4" href="/disclosures">Disclosures</Link></div></Panel></Container></Section>

      <Section className="border-t border-[var(--n100-border-subtle)]"><Container size="reading"><div className="text-center"><p className="font-mono text-[0.625rem] font-semibold uppercase tracking-[0.18em] text-[var(--n100-radar)]">Next step</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.045em] text-[var(--n100-text-primary)]">The public feed will open when the evidence path is ready.</h2><p className="mt-5 text-sm leading-6 text-[var(--n100-text-secondary)]">Until then, this page remains an honest product explanation with no fictional records, invented metrics, or implied action.</p><Link className="mt-7 inline-flex min-h-10 items-center justify-center rounded-[var(--n100-radius-control)] border border-[var(--n100-border-strong)] px-4 text-sm font-semibold text-[var(--n100-text-primary)] hover:border-[var(--n100-accent)] hover:text-[var(--n100-accent)]" href="/methodology">Read the full methodology</Link></div></Container></Section>
    </div>
  );
}
