begin;
\ir ../fixtures/analyzer.inc
select extensions.no_plan();
select extensions.ok((analyzer_read_state()->>'enabled')='false','Master default OFF');
select extensions.ok(not has_function_privilege('authenticated','public.analyzer_submit_run(jsonb)','EXECUTE'),'Ambiguous old persistence is inaccessible');
select extensions.ok(not has_table_privilege('authenticated','public.analyzer_delivery_intents','SELECT,INSERT,UPDATE,DELETE'),'Reservations are not browser tables');
select extensions.throws_ok($$select public.analyzer_reserve_delivery((select f->'input' from analyzer_case),(select f->'resolution' from analyzer_case))$$,'55000',null,'Direct reservation while OFF rejected');
select public.set_token_analyzer_enabled(true);
select extensions.throws_ok($$select public.analyzer_reserve_delivery(jsonb_set((select f->'input' from analyzer_case),'{raw}','"0x0000000000000000000000000000000000000002"'),(select f->'resolution' from analyzer_case))$$,'23P01',null,'Raw A resolved B rejected at canonical boundary');
select extensions.throws_ok($$select public.analyzer_reserve_delivery((select f->'input' from analyzer_case),jsonb_set((select f->'resolution' from analyzer_case),'{canonicalTokenId}','"ethereum:invalid"'))$$,'23P01',null,'Canonical identity mismatch rejected');
select extensions.throws_ok($$select public.analyzer_reserve_delivery('{"raw":"invalid","hintChain":"ethereum"}',jsonb_set(jsonb_set((select f->'resolution' from analyzer_case),'{tokenAddress}','"invalid"'),'{canonicalTokenId}','"ethereum:invalid"'))$$,'23P01',null,'Caller-consistent invalid address rejected');
update analyzer_case set r=public.analyzer_reserve_delivery(f->'input',f->'resolution');
select extensions.is((select public.analyzer_reserve_delivery(f->'input',f->'resolution')->>'status' from analyzer_case),'EXISTING_IN_PROGRESS','Routine calls join owner');
select extensions.ok(not ((select public.analyzer_reserve_delivery(f->'input',f->'resolution') from analyzer_case) ? 'owner_token'),'Joiner cannot receive completion capability');
select extensions.throws_ok($$select public.analyzer_complete_delivery((select r->>'delivery_key' from analyzer_case),'00000000-0000-4000-8000-000000000000',(select f->'manifest' from analyzer_case))$$,'23P01',null,'Non-owner completion rejected');
select public.set_token_analyzer_enabled(false);
select extensions.throws_ok($$select public.analyzer_complete_delivery((select r->>'delivery_key' from analyzer_case),(select (r->>'owner_token')::uuid from analyzer_case),(select f->'manifest' from analyzer_case))$$,'55000',null,'Disable before completion fails closed');
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000987702","role":"authenticated"}',true);
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000987702',true);
select extensions.throws_ok($$select public.analyzer_reserve_delivery((select f->'input' from analyzer_case),(select f->'resolution' from analyzer_case))$$,'42501',null,'Ordinary authenticated user rejected');
select * from extensions.finish();
rollback;
