"use server";

import { revalidatePath } from "next/cache";
import { getAuthorizationContext, type RoleKey } from "@/lib/auth/authorization";
import { sha256 } from "@/lib/radar/hash";

export type RadarActionResult = { ok: true } | { ok: false; error: string };
const reviewers: readonly RoleKey[] = ["owner", "admin", "radar_reviewer"];
const processors: readonly RoleKey[] = [...reviewers, "analyst"];
function hasRole(roles: readonly RoleKey[], accepted: readonly RoleKey[]) { return roles.some((role) => accepted.includes(role)); }
function errorMessage(error: { code?: string | null } | null) { switch (error?.code) { case "40001": return "This Radar record changed. Refresh before trying again."; case "42501": return "You are not authorized for this Radar operation."; case "55000": return "This Radar operation is not available in the current state."; case "22023": case "23514": return "Check the provided Radar operation details."; default: return "The Radar operation could not be completed."; } }
function revalidateRadar() { revalidatePath("/admin/radar"); revalidatePath("/radar"); revalidatePath("/radar-preview"); }
function bounded(value: string, max: number) { return value.trim().slice(0, max); }
function intent(value: string) { if (typeof value !== "string" || !/^[A-Za-z0-9_-]{8,128}$/.test(value)) throw new Error("A valid operation intent is required."); return value; }
function actionKey(actor: string, action: string, target: string, payload: unknown, operationIntent: string) { return `${action}:${sha256({ actor, action, target, payload, intent: operationIntent })}`; }

export async function approveRadarReview(reviewId: string, revision: number, publicNote: string, disclosure: string, operationIntent: string): Promise<RadarActionResult> {
  try { const context = await getAuthorizationContext(); if (!hasRole(context.roles, reviewers)) return { ok: false, error: "You are not authorized to approve Radar reviews." }; const safeIntent = intent(operationIntent); const { error } = await context.supabase.rpc("radar_approve_review", { p_review_id: reviewId, p_expected_revision: revision, p_public_note: bounded(publicNote, 2000), p_public_disclosure: bounded(disclosure, 2000), p_action_key: actionKey(context.userId, "approve", reviewId, { revision, publicNote: bounded(publicNote, 2000), disclosure: bounded(disclosure, 2000) }, safeIntent) }); if (error) return { ok: false, error: errorMessage(error) }; revalidateRadar(); return { ok: true }; } catch { return { ok: false, error: "Radar administration is temporarily unavailable." }; }
}
export async function publishRadarReview(reviewId: string, revision: number, operationIntent: string): Promise<RadarActionResult> {
  try { const context = await getAuthorizationContext(); if (!hasRole(context.roles, reviewers)) return { ok: false, error: "You are not authorized to publish Radar reviews." }; const { error } = await context.supabase.rpc("radar_publish_review", { p_review_id: reviewId, p_expected_revision: revision, p_action_key: actionKey(context.userId, "publish", reviewId, { revision }, intent(operationIntent)) }); if (error) return { ok: false, error: errorMessage(error) }; revalidateRadar(); return { ok: true }; } catch { return { ok: false, error: "Radar administration is temporarily unavailable." }; }
}
export async function rejectRadarReview(reviewId: string, revision: number, reason: string, operationIntent: string): Promise<RadarActionResult> {
  try { const context = await getAuthorizationContext(); if (!hasRole(context.roles, reviewers)) return { ok: false, error: "You are not authorized to reject Radar reviews." }; const safeReason = bounded(reason, 1000); const { error } = await context.supabase.rpc("radar_reject_review", { p_review_id: reviewId, p_expected_revision: revision, p_reason: safeReason, p_action_key: actionKey(context.userId, "reject", reviewId, { revision, reason: safeReason }, intent(operationIntent)) }); if (error) return { ok: false, error: errorMessage(error) }; revalidateRadar(); return { ok: true }; } catch { return { ok: false, error: "Radar administration is temporarily unavailable." }; }
}
export async function hideRadarReview(reviewId: string, revision: number, reason: string, operationIntent: string): Promise<RadarActionResult> {
  try { const context = await getAuthorizationContext(); if (!hasRole(context.roles, reviewers)) return { ok: false, error: "You are not authorized to hide Radar reviews." }; const safeReason = bounded(reason, 1000); const { error } = await context.supabase.rpc("radar_hide_review", { p_review_id: reviewId, p_expected_revision: revision, p_reason: safeReason, p_action_key: actionKey(context.userId, "hide", reviewId, { revision, reason: safeReason }, intent(operationIntent)) }); if (error) return { ok: false, error: errorMessage(error) }; revalidateRadar(); return { ok: true }; } catch { return { ok: false, error: "Radar administration is temporarily unavailable." }; }
}
export async function updateRadarEditorialNote(reviewId: string, revision: number, note: string, operationIntent: string): Promise<RadarActionResult> {
  try { const context = await getAuthorizationContext(); if (!hasRole(context.roles, reviewers)) return { ok: false, error: "You are not authorized to edit Radar notes." }; const safeNote = bounded(note, 4000); const { error } = await context.supabase.rpc("radar_update_editorial_note", { p_review_id: reviewId, p_expected_revision: revision, p_editorial_note: safeNote, p_action_key: actionKey(context.userId, "note", reviewId, { revision, note: safeNote }, intent(operationIntent)) }); if (error) return { ok: false, error: errorMessage(error) }; revalidateRadar(); return { ok: true }; } catch { return { ok: false, error: "Radar administration is temporarily unavailable." }; }
}
export async function requestRadarReanalysis(analysisId: string, reason: string, operationIntent: string): Promise<RadarActionResult> {
  try { const context = await getAuthorizationContext(); if (!hasRole(context.roles, processors)) return { ok: false, error: "You are not authorized to request Radar reanalysis." }; const safeReason = bounded(reason, 1000); const { error } = await context.supabase.rpc("radar_request_reanalysis", { p_analysis_id: analysisId, p_reason: safeReason, p_request_key: actionKey(context.userId, "reanalysis", analysisId, { reason: safeReason }, intent(operationIntent)) }); if (error) return { ok: false, error: errorMessage(error) }; revalidateRadar(); return { ok: true }; } catch { return { ok: false, error: "Radar administration is temporarily unavailable." }; }
}
export async function requestRadarScoreRecalculation(analysisId: string, reason: string, operationIntent: string): Promise<RadarActionResult> {
  try { const context = await getAuthorizationContext(); if (!hasRole(context.roles, processors)) return { ok: false, error: "You are not authorized to request Radar score recalculation." }; const safeReason = bounded(reason, 1000); const { error } = await context.supabase.rpc("radar_request_score_recalculation", { p_analysis_id: analysisId, p_reason: safeReason, p_request_key: actionKey(context.userId, "recalculation", analysisId, { reason: safeReason }, intent(operationIntent)) }); if (error) return { ok: false, error: errorMessage(error) }; revalidateRadar(); return { ok: true }; } catch { return { ok: false, error: "Radar administration is temporarily unavailable." }; }
}
