"use client";

import { useState, useTransition } from "react";
import { approveRadarReview, hideRadarReview, publishRadarReview, rejectRadarReview, requestRadarReanalysis, requestRadarScoreRecalculation, updateRadarEditorialNote, type RadarActionResult } from "@/app/admin/radar/actions";
import type { RadarAdminRecord } from "@/lib/radar/admin-types";
import { Button, Panel, StatusLabel } from "@/components/ui";

function Feedback({ result }: { result: RadarActionResult | null }) { return result && !result.ok ? <p role="alert" className="mt-3 text-xs text-[var(--n100-negative)]">{result.error}</p> : result?.ok ? <p role="status" className="mt-3 text-xs text-[var(--n100-positive)]">Operation accepted. Refreshing the queue.</p> : null; }
function newIntent() { return globalThis.crypto.randomUUID(); }

export default function RadarOperations({ record, canReview, canProcess }: { record: RadarAdminRecord; canReview: boolean; canProcess: boolean }) {
  const [pending, startTransition] = useTransition(); const [result, setResult] = useState<RadarActionResult | null>(null);
  const [note, setNote] = useState(record.editorialNote ?? ""); const [publicNote, setPublicNote] = useState(record.publicNote ?? ""); const [disclosure, setDisclosure] = useState(record.publicDisclosure ?? "");
  const run = (operation: () => Promise<RadarActionResult>) => { setResult(null); startTransition(async () => setResult(await operation())); };
  const revision = record.reviewRevision ?? 1;
  return <Panel family="radar" padding="md" className="mt-4">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><StatusLabel kind="radar" /><span className="font-mono text-[0.625rem] uppercase tracking-[0.12em] text-[var(--n100-text-tertiary)]">Analysis v{record.analysisVersion} · {record.reviewState ?? "NO REVIEW"}</span></div><h2 className="mt-3 text-lg font-semibold">{record.name || record.symbol || record.contractAddress}</h2><p className="mt-1 font-mono text-xs text-[var(--n100-text-tertiary)]">{record.chain} · {record.contractAddress}</p></div><div className="text-right"><p className="font-mono text-2xl text-[var(--n100-text-primary)]">{record.score ?? "—"}</p><p className="text-xs text-[var(--n100-text-tertiary)]">Score snapshot · never manually edited</p></div></div>
    <div className="mt-5 grid gap-3 text-sm sm:grid-cols-4"><div><p className="text-xs text-[var(--n100-text-tertiary)]">Status</p><p className="mt-1">{record.status}</p></div><div><p className="text-xs text-[var(--n100-text-tertiary)]">Screening</p><p className="mt-1">{record.screeningResult ?? "—"}</p></div><div><p className="text-xs text-[var(--n100-text-tertiary)]">Evidence</p><p className="mt-1">{record.evidenceCount} bound item{record.evidenceCount === 1 ? "" : "s"}</p></div><div><p className="text-xs text-[var(--n100-text-tertiary)]">Freshness</p><p className="mt-1">{record.publicEligible ? "Eligibility recorded" : "Not eligible"}</p></div></div>
    {record.riskSummary ? <p className="mt-4 border-l-2 border-[var(--n100-radar)]/50 pl-3 text-sm leading-6 text-[var(--n100-text-secondary)]">{record.riskSummary}</p> : null}
    {canReview && record.reviewId && record.reviewState ? <div className="mt-6 grid gap-4 border-t border-[var(--n100-border-subtle)] pt-5 lg:grid-cols-2"><label className="text-xs text-[var(--n100-text-tertiary)]">Public note<textarea value={publicNote} onChange={(event) => setPublicNote(event.target.value)} className="mt-2 min-h-20 w-full rounded border border-[var(--n100-border-strong)] bg-transparent p-2 text-sm text-[var(--n100-text-primary)]" maxLength={2000} /></label><label className="text-xs text-[var(--n100-text-tertiary)]">Public disclosure<textarea value={disclosure} onChange={(event) => setDisclosure(event.target.value)} className="mt-2 min-h-20 w-full rounded border border-[var(--n100-border-strong)] bg-transparent p-2 text-sm text-[var(--n100-text-primary)]" maxLength={2000} /></label><label className="text-xs text-[var(--n100-text-tertiary)] lg:col-span-2">Editorial note<textarea value={note} onChange={(event) => setNote(event.target.value)} className="mt-2 min-h-20 w-full rounded border border-[var(--n100-border-strong)] bg-transparent p-2 text-sm text-[var(--n100-text-primary)]" maxLength={4000} /></label><div className="flex flex-wrap gap-2 lg:col-span-2">
      {record.reviewState === "PENDING" ? <><Button size="sm" variant="primary" loading={pending} onClick={() => run(() => approveRadarReview(record.reviewId!, revision, publicNote, disclosure, newIntent()))}>Approve review</Button><Button size="sm" variant="destructive" loading={pending} onClick={() => run(() => rejectRadarReview(record.reviewId!, revision, "Rejected during editorial review.", newIntent()))}>Reject</Button></> : null}
      {record.reviewState === "APPROVED" ? <Button size="sm" variant="primary" loading={pending} onClick={() => run(() => publishRadarReview(record.reviewId!, revision, newIntent()))}>Publish</Button> : null}
      {record.reviewState === "PUBLISHED" ? <Button size="sm" variant="destructive" loading={pending} onClick={() => run(() => hideRadarReview(record.reviewId!, revision, "Hidden during editorial review.", newIntent()))}>Hide publication</Button> : null}
      {record.reviewState !== "PUBLISHED" ? <Button size="sm" variant="secondary" loading={pending} onClick={() => run(() => updateRadarEditorialNote(record.reviewId!, revision, note, newIntent()))}>Save editorial note</Button> : null}
    </div></div> : null}
    {canProcess ? <div className="mt-5 flex flex-wrap gap-2 border-t border-[var(--n100-border-subtle)] pt-5"><Button size="sm" variant="ghost" loading={pending} onClick={() => run(() => requestRadarReanalysis(record.analysisId, "Requested from Radar operations.", newIntent()))}>Request reanalysis</Button><Button size="sm" variant="ghost" loading={pending} onClick={() => run(() => requestRadarScoreRecalculation(record.analysisId, "Requested from Radar operations.", newIntent()))}>Request score recalculation</Button></div> : null}
    <Feedback result={result} />
  </Panel>;
}
