"use client";

import { useState, useTransition } from "react";
import { Button, Metric, Panel } from "@/components/ui";
import { analyzeToken, updateAnalyzerEnabled } from "@/app/admin/token-analyzer/actions";
import type { AnalyzerResult } from "@/lib/token-analyzer/contracts";

export default function TokenAnalyzerConsole({ initialEnabled, publicEnabled, analysisCount }: { initialEnabled: boolean; publicEnabled: boolean; analysisCount: number }) {
  const [enabled, setEnabled] = useState(initialEnabled); const [raw, setRaw] = useState(""); const [chain, setChain] = useState("unknown"); const [result, setResult] = useState<AnalyzerResult | null>(null); const [message, setMessage] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  function toggle() { startTransition(async () => { const response = await updateAnalyzerEnabled(!enabled); if (response.ok) { setEnabled(Boolean(response.enabled)); setMessage(response.enabled ? "Analyzer enabled for new internal runs." : "Analyzer disabled; new runs fail closed."); } else setMessage(response.error); }); }
  function run() { startTransition(async () => { setMessage(null); const response = await analyzeToken({ raw, hintChain: chain as "unknown" | "solana" | "ethereum" | "base" | "bnb" }); if (!response.ok) setMessage(response.error); else if (response.result) setResult(response.result); }); }
  return <div className="space-y-6">
    <Panel family="admin" padding="lg"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-[0.625rem] uppercase tracking-[0.14em] text-[var(--n100-accent)]">Master control</p><h2 className="mt-2 text-xl font-semibold">Internal Analyzer availability</h2><p className="mt-2 text-sm text-[var(--n100-text-tertiary)]">Only Owner/Admin can change this audited switch. Public access remains separately disabled.</p></div><Button variant={enabled ? "destructive" : "primary"} onClick={toggle} loading={pending}>{enabled ? "Disable Analyzer" : "Enable Analyzer"}</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Master" value={enabled ? "ON" : "OFF"} tone={enabled ? "positive" : "neutral"} /><Metric label="Public" value={publicEnabled ? "ON · BLOCKED BY POLICY" : "OFF"} /><Metric label="Analyses" value={String(analysisCount)} /></div></Panel>
    <Panel padding="lg"><p className="font-mono text-[0.625rem] uppercase tracking-[0.14em] text-[var(--n100-accent)]">Internal test console</p><h2 className="mt-2 text-xl font-semibold">Resolve and analyze an input</h2><p className="mt-2 text-sm text-[var(--n100-text-tertiary)]">No public route, publication, trading, or AI call is attached to this console.</p><div className="mt-5 grid gap-4 sm:grid-cols-[1fr_12rem_auto]"><input aria-label="Analyzer input" className="min-h-10 rounded border border-[var(--n100-border-strong)] bg-transparent px-3 text-sm" placeholder="Contract, mint, DEX link, chart link, or article URL" value={raw} onChange={(event) => setRaw(event.target.value)} /><select aria-label="Analyzer chain" className="min-h-10 rounded border border-[var(--n100-border-strong)] bg-transparent px-3 text-sm" value={chain} onChange={(event) => setChain(event.target.value)}><option value="unknown">Auto detect</option><option value="solana">Solana</option><option value="ethereum">Ethereum</option><option value="base">Base</option><option value="bnb">BNB Chain</option></select><Button onClick={run} loading={pending} disabled={!raw.trim()}>Analyze</Button></div>{message ? <p className="mt-4 text-sm text-[var(--n100-negative)]">{message}</p> : null}</Panel>
    {result ? <AnalyzerResultView result={result} /> : <Panel padding="lg"><p className="text-sm text-[var(--n100-text-tertiary)]">Run an internal analysis to inspect the identity, evidence gaps, score contract, and provider boundary.</p></Panel>}
  </div>;
}
function AnalyzerResultView({ result }: { result: AnalyzerResult }) { return <div className="grid gap-6 lg:grid-cols-2"><Panel padding="lg"><p className="font-mono text-[0.625rem] uppercase tracking-[0.14em] text-[var(--n100-accent)]">Result</p><h2 className="mt-2 text-xl font-semibold">{result.resolvedToken.tokenAddress ?? "Token not resolved"}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><Metric label="Status" value={result.status} /><Metric label="Chain" value={result.chain} /><Metric label="Confidence" value={`${result.dataConfidence.state} · ${result.dataConfidence.coverage}%`} /><Metric label="Freshness" value={result.freshness.state} /><Metric label="Score" value={result.score.status === "METHODOLOGY_NOT_ACTIVE" ? "NO SCORE" : String(result.score.value)} /><Metric label="Evidence" value={`${result.evidenceSummary.available}/${result.evidenceSummary.total} available`} /></div></Panel><Panel padding="lg"><p className="font-mono text-[0.625rem] uppercase tracking-[0.14em] text-[var(--n100-accent)]">Why moving / unknowns</p><p className="mt-3 text-sm text-[var(--n100-text-secondary)]">{result.whyMoving[0]?.explanation}</p><ul className="mt-4 list-disc space-y-1 pl-5 text-sm text-[var(--n100-text-tertiary)]">{result.unknowns.map((item) => <li key={item}>{item}</li>)}</ul><p className="mt-4 text-xs text-[var(--n100-text-tertiary)]">{result.score.status === "METHODOLOGY_NOT_ACTIVE" ? "Methodology validation is in progress; no Radar Score is calculated." : ""}</p></Panel></div>; }
