"use client";

import { useState, useTransition } from "react";
import { Button, Metric, Panel } from "@/components/ui";
import { analyzeToken, updateAnalyzerEnabled } from "@/app/admin/token-analyzer/actions";
import type { AnalyzerResult } from "@/lib/token-analyzer/contracts";

export default function TokenAnalyzerConsole({ initialEnabled, publicEnabled, analysisCount }: { initialEnabled: boolean; publicEnabled: boolean; analysisCount: number }) {
  const [telemetry, setTelemetry] = useState<unknown[]>([]);
  const [enabled, setEnabled] = useState(initialEnabled); const [raw, setRaw] = useState(""); const [chain, setChain] = useState("unknown"); const [result, setResult] = useState<AnalyzerResult | null>(null); const [message, setMessage] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  function toggle() { startTransition(async () => { const response = await updateAnalyzerEnabled(!enabled); if (response.ok) { setEnabled(Boolean(response.enabled)); setMessage(response.enabled ? "Analyzer enabled for new internal runs." : "Analyzer disabled; new runs fail closed."); } else setMessage(response.error); }); }
  function run() { startTransition(async () => { setMessage(null); const response = await analyzeToken({ raw, hintChain: chain as "unknown" | "solana" | "ethereum" | "base" | "bnb" }); if (!response.ok) setMessage(response.error); else if (response.result) { setResult(response.result); setTelemetry(response.telemetry ?? []); } }); }
  return <div className="space-y-6">
    <Panel family="admin" padding="lg"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-[0.625rem] uppercase tracking-[0.14em] text-[var(--n100-accent)]">Master control</p><h2 className="mt-2 text-xl font-semibold">Internal Analyzer availability</h2><p className="mt-2 text-sm text-[var(--n100-text-tertiary)]">Only Owner/Admin can change this audited switch. Public access remains separately disabled.</p></div><Button variant={enabled ? "destructive" : "primary"} onClick={toggle} loading={pending}>{enabled ? "Disable Analyzer" : "Enable Analyzer"}</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Master" value={enabled ? "ON" : "OFF"} tone={enabled ? "positive" : "neutral"} /><Metric label="Public" value={publicEnabled ? "ON · BLOCKED BY POLICY" : "OFF"} /><Metric label="Analyses" value={String(analysisCount)} /></div></Panel>
    <Panel padding="lg"><p className="font-mono text-[0.625rem] uppercase tracking-[0.14em] text-[var(--n100-accent)]">Internal test console</p><h2 className="mt-2 text-xl font-semibold">Resolve and analyze an input</h2><p className="mt-2 text-sm text-[var(--n100-text-tertiary)]">No public route, publication, trading, or AI call is attached to this console.</p><div className="mt-5 grid gap-4 sm:grid-cols-[1fr_12rem_auto]"><input aria-label="Analyzer input" className="min-h-10 rounded border border-[var(--n100-border-strong)] bg-transparent px-3 text-sm" placeholder="Contract, mint, DEX link, chart link, or article URL" value={raw} onChange={(event) => setRaw(event.target.value)} /><select aria-label="Analyzer chain" className="min-h-10 rounded border border-[var(--n100-border-strong)] bg-transparent px-3 text-sm" value={chain} onChange={(event) => setChain(event.target.value)}><option value="unknown">Auto detect</option><option value="solana">Solana</option><option value="ethereum">Ethereum</option><option value="base">Base</option><option value="bnb">BNB Chain</option></select><Button onClick={run} loading={pending} disabled={!raw.trim()}>Analyze</Button></div>{message ? <p className="mt-4 text-sm text-[var(--n100-negative)]">{message}</p> : null}</Panel>
    {result ? <AnalyzerResultView result={result} telemetry={telemetry} /> : <Panel padding="lg"><p className="text-sm text-[var(--n100-text-tertiary)]">Run an internal analysis to inspect the identity, evidence gaps, score contract, and provider boundary.</p></Panel>}
  </div>;
}
function formatDetail(value: unknown) { if (value === null || value === undefined) return "UNKNOWN"; if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") return String(value); return JSON.stringify(value, null, 2); }
function DetailPanel({ title, value }: { title: string; value: unknown }) {
  const entries = value && typeof value === "object" && !Array.isArray(value) ? Object.entries(value as Record<string, unknown>) : [];
  return <Panel padding="lg"><p className="font-mono text-[0.625rem] uppercase tracking-[0.14em] text-[var(--n100-accent)]">{title}</p>{entries.length ? <div className="mt-4 space-y-3">{entries.map(([key, item]) => <div key={key} className="rounded border border-[var(--n100-border-subtle)] p-3"><p className="text-xs font-medium uppercase tracking-wide text-[var(--n100-text-tertiary)]">{key}</p><pre className="mt-1 whitespace-pre-wrap break-words text-xs text-[var(--n100-text-secondary)]">{formatDetail(item)}</pre></div>)}</div> : <p className="mt-3 text-sm text-[var(--n100-text-tertiary)]">UNKNOWN</p>}</Panel>;
}
function AnalyzerResultView({ result, telemetry }: { result: AnalyzerResult; telemetry: unknown[] }) {
  return <div className="space-y-6">
    <div className="grid gap-6 lg:grid-cols-2">
      <Panel padding="lg"><p className="font-mono text-[0.625rem] uppercase tracking-[0.14em] text-[var(--n100-accent)]">Resolution</p><h2 className="mt-2 break-all text-xl font-semibold">{result.resolvedToken.tokenAddress ?? "Token not resolved"}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><Metric label="Status" value={result.status} /><Metric label="Chain" value={result.chain} /><Metric label="Input" value={result.resolvedToken.inputType} /><Metric label="Confidence" value={`${result.dataConfidence.state} · ${result.dataConfidence.coverage}%`} /><Metric label="Freshness" value={result.freshness.state} /><Metric label="Evidence" value={`${result.evidenceSummary.available}/${result.evidenceSummary.total} available`} /></div><p className="mt-4 break-all text-xs text-[var(--n100-text-tertiary)]">Pair: {result.pair.address ?? "UNKNOWN"} · Pool: {result.pair.pool ?? "UNKNOWN"}</p></Panel>
      <Panel padding="lg"><p className="font-mono text-[0.625rem] uppercase tracking-[0.14em] text-[var(--n100-accent)]">Why moving / data gaps</p><div className="mt-3 space-y-2">{result.whyMoving.map((item, index) => <div key={`${item.classification}-${index}`}><p className="text-xs font-medium uppercase tracking-wide text-[var(--n100-text-tertiary)]">{item.classification}</p><p className="text-sm text-[var(--n100-text-secondary)]">{item.explanation}</p></div>)}</div><ul className="mt-4 list-disc space-y-1 pl-5 text-sm text-[var(--n100-text-tertiary)]">{result.unknowns.map((item) => <li key={item}>{item}</li>)}</ul></Panel>
    </div>
    <div className="grid gap-6 lg:grid-cols-2"><DetailPanel title="Token / market" value={{ symbol: result.resolvedToken.symbol, name: result.resolvedToken.name, decimals: result.market.decimals, supply: result.market.supply, price: result.market.price, marketCap: result.market.marketCap, fdv: result.market.fdv, volume: result.market.volume, transactions: result.market.transactions }} /><DetailPanel title="Lifecycle" value={result.lifecycle} /></div>
    <div className="grid gap-6 lg:grid-cols-3"><DetailPanel title="Liquidity" value={result.liquidity} /><DetailPanel title="Holders / distribution" value={result.holders} /><DetailPanel title="Creator / activity" value={{ creator: result.creator, activity: result.activity }} /></div>
    <div className="grid gap-6 lg:grid-cols-2"><DetailPanel title="Top trades" value={result.topTrades.length ? result.topTrades : { status: "UNKNOWN", reason: "No trustworthy trade capability was configured for this analysis." }} /><DetailPanel title="Provider conflicts" value={result.providerConflicts.length ? result.providerConflicts : { status: "NONE_RECORDED" }} /></div>
    <div className="grid gap-6 lg:grid-cols-2"><DetailPanel title="Provider usage" value={{ operations: telemetry, note: "Operational telemetry is separate from the sealed receipt." }} /><DetailPanel title="Score / AI" value={{ score: result.score.status === "METHODOLOGY_NOT_ACTIVE" ? "NO SCORE" : result.score, ai: result.aiInterpretation, methodology: "INACTIVE" }} /></div>
  </div>;
}
