import { normalizeDecimal, normalizeInteger } from "@/lib/radar/decimal";
import { sha256 } from "@/lib/radar/hash";
import { RADAR_DATA_STATES, type RadarDataState, type RadarNormalizedObservation, type RadarProviderObservation } from "@/lib/radar/contracts";
const ID = /^[a-z][a-z0-9_.:-]{1,63}$/; const VERSION = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;
export class RadarNormalizationError extends Error { constructor(message: string) { super(message); this.name = "RadarNormalizationError"; } }
function identifier(value: string, label: string, pattern = ID) { if (typeof value !== "string" || !pattern.test(value)) throw new RadarNormalizationError(`${label} has an invalid identifier.`); return value; }
function timestamp(value: string, label: string) { if (!/^\d{4}-\d\d-\d\dT/.test(value) || !Number.isFinite(Date.parse(value))) throw new RadarNormalizationError(`${label} must be an ISO timestamp.`); return new Date(value).toISOString(); }
function flatMap(value: RadarProviderObservation["provenance"], label: string) { if (value === undefined) return {}; if (!value || Array.isArray(value) || Object.keys(value).length > 8) throw new RadarNormalizationError(`${label} must be a bounded flat object.`); for (const item of Object.values(value)) if (item !== null && !["string", "number", "boolean"].includes(typeof item)) throw new RadarNormalizationError(`${label} must contain scalar values only.`); return value; }
export function normalizeProviderObservation(observation: RadarProviderObservation, receivedAt = new Date().toISOString()): RadarNormalizedObservation { if (!RADAR_DATA_STATES.includes(observation.state as RadarDataState)) throw new RadarNormalizationError("Provider returned an unsupported data state."); const state = observation.state; const value = observation.value === undefined ? null : normalizeDecimal(observation.value, "observation value"); const rawIntegerValue = observation.rawIntegerValue === undefined ? null : normalizeInteger(observation.rawIntegerValue, "raw integer value"); if (state === "AVAILABLE" && value === null) throw new RadarNormalizationError("AVAILABLE observations require a value."); if (state !== "AVAILABLE" && value !== null) throw new RadarNormalizationError("Unavailable observations cannot carry a numeric value."); if (state !== "AVAILABLE" && !observation.reason?.trim()) throw new RadarNormalizationError("Non-available observations require an explicit reason."); if (observation.decimalPlaces !== undefined && (!Number.isInteger(observation.decimalPlaces) || observation.decimalPlaces < 0 || observation.decimalPlaces > 255)) throw new RadarNormalizationError("decimalPlaces is outside the supported range."); const normalized = { provider: identifier(observation.provider, "provider"), adapterVersion: identifier(observation.adapterVersion, "adapter version", VERSION), capability: identifier(observation.capability, "capability"), metricKey: identifier(observation.metricKey, "metric key"), state, value, rawIntegerValue, decimalPlaces: observation.decimalPlaces ?? null, unit: observation.unit?.trim() || null, context: flatMap(observation.context, "context"), provenance: flatMap({ ...(observation.provenance ?? {}), ...(observation.reason ? { reason: observation.reason } : {}) }, "provenance"), traceReference: observation.traceReference ?? null, observedAt: timestamp(observation.observedAt, "observedAt"), receivedAt: timestamp(receivedAt, "receivedAt") }; return { ...normalized, contentHash: sha256(normalized) }; }
