export type PublicRadarMetric = { metricKey: string; category: string; value: string | null; state: string; observedAt: string | null; source: string | null };
export type PublicRadarEvidence = { classification: "VERIFIED_DATA" | "STRONG_SIGNAL" | "AI_INFERENCE" | "UNKNOWN"; category: string; label: string; statement: string | null; value: string | null; unit: string | null; source: string | null; sourceReference: string | null; observedAt: string | null };
export type PublicRadarRecord = { tokenId: string; chain: string; contractAddress: string; symbol: string | null; name: string | null; analyticalStatus: "EARLY" | "TRENDING" | "HIGH_RISK"; score: string | null; methodologyVersion: string | null; analysisVersion: number; calculatedAt: string | null; asOf: string | null; freshnessState: "FRESH" | "STALE"; whyOnRadar: string | null; riskSummary: string | null; metrics: readonly PublicRadarMetric[]; evidence: readonly PublicRadarEvidence[]; publicNote: string | null; disclosure: string | null; publishedAt: string | null };
export type PublicRadarFeed = { state: "READY" | "EMPTY" | "UNAVAILABLE"; records: readonly PublicRadarRecord[] };

function object(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function stringValue(value: unknown): string | null { return typeof value === "string" && value.length > 0 ? value : null; }
function oneOf<T extends string>(value: unknown, allowed: readonly T[]): T | null { return typeof value === "string" && allowed.includes(value as T) ? value as T : null; }
function mapMetric(value: unknown): PublicRadarMetric | null { const item = object(value); const metricKey = stringValue(item.metric_key); const category = stringValue(item.category); const state = stringValue(item.state); if (!metricKey || !category || !state) return null; return { metricKey, category, value: stringValue(item.value), state, observedAt: stringValue(item.observed_at), source: stringValue(item.source) }; }
function mapEvidence(value: unknown): PublicRadarEvidence | null { const item = object(value); const classification = oneOf(item.classification, ["VERIFIED_DATA", "STRONG_SIGNAL", "AI_INFERENCE", "UNKNOWN"] as const); const category = stringValue(item.category); const label = stringValue(item.label); if (!classification || !category || !label) return null; return { classification, category, label, statement: stringValue(item.statement), value: stringValue(item.value), unit: stringValue(item.unit), source: stringValue(item.source), sourceReference: stringValue(item.source_reference), observedAt: stringValue(item.observed_at) }; }

export function mapPublicRadarRow(value: unknown): PublicRadarRecord | null {
  const item = object(value); const tokenId = stringValue(item.token_id); const chain = stringValue(item.chain); const contractAddress = stringValue(item.contract_address); const status = oneOf(item.analytical_status, ["EARLY", "TRENDING", "HIGH_RISK"] as const); const freshnessState = oneOf(item.freshness_state, ["FRESH", "STALE"] as const); const analysisVersion = typeof item.analysis_version === "number" && Number.isInteger(item.analysis_version) ? item.analysis_version : null;
  if (!tokenId || !chain || !contractAddress || !status || !freshnessState || analysisVersion === null) return null;
  const metrics = Array.isArray(item.metrics) ? item.metrics.map(mapMetric).filter((entry): entry is PublicRadarMetric => entry !== null).slice(0, 64) : [];
  const evidence = Array.isArray(item.evidence) ? item.evidence.map(mapEvidence).filter((entry): entry is PublicRadarEvidence => entry !== null).slice(0, 64) : [];
  return { tokenId, chain, contractAddress, symbol: stringValue(item.symbol), name: stringValue(item.name), analyticalStatus: status, score: stringValue(item.score), methodologyVersion: stringValue(item.methodology_version), analysisVersion, calculatedAt: stringValue(item.calculated_at), asOf: stringValue(item.as_of), freshnessState, whyOnRadar: stringValue(item.why_on_radar), riskSummary: stringValue(item.risk_summary), metrics, evidence, publicNote: stringValue(item.public_note), disclosure: stringValue(item.disclosure), publishedAt: stringValue(item.published_at) };
}
