import "server-only";
import { createClient as createSupabaseClient, type SupabaseClient } from "@supabase/supabase-js";
import type { RadarFastLaneResult, RadarNormalizedObservation } from "@/lib/radar/contracts";
export class RadarSystemGatewayError extends Error { constructor(message: string) { super(message); this.name = "RadarSystemGatewayError"; } }
export type RadarClaimedWork = { workItemId: string; workKind: string; tokenId: string | null; leaseToken: string; leaseGeneration: number; pauseGeneration: number };
export type RadarSystemGateway = { insertEvent(input: { eventKey: string; eventType: string; tokenId: string | null; sourceProvider: string; sourceEventId: string | null; payloadHash: string; context: Record<string, unknown>; observedAt: string }): Promise<string>; recordObservation(input: { eventId: string; tokenId: string | null; observation: RadarNormalizedObservation }): Promise<string>; enqueueWork(input: { requestKey: string; workKind: string; tokenId: string | null; eventId: string | null; parentAnalysisId: string | null; methodVersion: string | null; inputVersion: string | null; availableAt?: string }): Promise<string>; attachObservation(workItemId: string, observationId: string): Promise<void>; claimWork(worker: string, leaseSeconds?: number): Promise<RadarClaimedWork | null>; completeScreening(input: { workItemId: string; worker: string; leaseToken: string; leaseGeneration: number; result: RadarFastLaneResult }): Promise<string>; renewWork(input: { workItemId: string; worker: string; leaseToken: string; leaseGeneration: number; leaseSeconds?: number }): Promise<boolean>; failWork(input: { workItemId: string; worker: string; leaseToken: string; leaseGeneration: number; retryable: boolean; summary: string; retryAt?: string }): Promise<string> };
let client: SupabaseClient | null | undefined;
function getClient(): SupabaseClient { if (client) return client; if (client === null) throw new RadarSystemGatewayError("Radar system credentials are not configured."); const url = process.env.SUPABASE_URL, secret = process.env.SUPABASE_SECRET_KEY; client = url && secret ? createSupabaseClient(url, secret, { auth: { autoRefreshToken: false, detectSessionInUrl: false, persistSession: false } }) : null; if (!client) throw new RadarSystemGatewayError("Radar system credentials are not configured."); return client; }
async function rpc<T>(name: string, args: Record<string, unknown>) { const { data, error } = await getClient().rpc(name, args); if (error) throw new RadarSystemGatewayError(`Radar system operation ${name} failed.`); return data as T; }
export function createRadarSystemGateway(): RadarSystemGateway { return { insertEvent: (i) => rpc("radar_system_insert_event", { p_event_key: i.eventKey, p_event_type: i.eventType, p_token_id: i.tokenId, p_source_provider: i.sourceProvider, p_source_event_id: i.sourceEventId, p_payload_hash: i.payloadHash, p_context: i.context, p_observed_at: i.observedAt }), recordObservation: (i) => rpc("radar_system_record_observation", { p_event_id: i.eventId, p_token_id: i.tokenId, p_provider: i.observation.provider, p_adapter_version: i.observation.adapterVersion, p_capability: i.observation.capability, p_metric_key: i.observation.metricKey, p_data_state: i.observation.state, p_normalized_value: i.observation.value, p_raw_integer_value: i.observation.rawIntegerValue, p_decimal_places: i.observation.decimalPlaces, p_unit: i.observation.unit, p_context: i.observation.context, p_provenance: i.observation.provenance, p_trace_reference: i.observation.traceReference, p_content_hash: i.observation.contentHash, p_observed_at: i.observation.observedAt }), enqueueWork: (i) => rpc("radar_system_enqueue_work", { p_request_key: i.requestKey, p_work_kind: i.workKind, p_token_id: i.tokenId, p_event_id: i.eventId, p_parent_analysis_id: i.parentAnalysisId, p_method_version: i.methodVersion, p_input_version: i.inputVersion, p_available_at: i.availableAt ?? null }), attachObservation: async (workItemId, observationId) => { await rpc("radar_system_attach_observation", { p_work_item_id: workItemId, p_observation_id: observationId }); }, claimWork: async (worker, leaseSeconds = 300) => { const rows = await rpc<Array<{ work_item_id: string; work_kind: string; token_id: string | null; lease_token: string; lease_generation: number; pause_generation: number }>>("radar_system_claim_work", { p_worker: worker, p_lease_seconds: leaseSeconds }); const row = rows?.[0]; return row ? { workItemId: row.work_item_id, workKind: row.work_kind, tokenId: row.token_id, leaseToken: row.lease_token, leaseGeneration: row.lease_generation, pauseGeneration: row.pause_generation } : null; }, completeScreening: (i) => rpc("radar_system_complete_screening", { p_work_item_id: i.workItemId, p_worker: i.worker, p_lease_token: i.leaseToken, p_lease_generation: i.leaseGeneration, p_result: i.result.result, p_reasons: i.result.reasons, p_input_hash: i.result.inputHash, p_evaluated_at: i.result.evaluatedAt }), renewWork: (i) => rpc("radar_system_renew_work", { p_work_item_id: i.workItemId, p_worker: i.worker, p_lease_token: i.leaseToken, p_lease_generation: i.leaseGeneration, p_lease_seconds: i.leaseSeconds ?? 300 }), failWork: (i) => rpc("radar_system_fail_work", { p_work_item_id: i.workItemId, p_worker: i.worker, p_lease_token: i.leaseToken, p_lease_generation: i.leaseGeneration, p_retryable: i.retryable, p_error_summary: i.summary, p_retry_at: i.retryAt ?? null }) }; }
